[package]
name = "modggl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

env_logger = "0.9.0"
log = "0.4.14"
actix-web = "3.3.3"
serde = "1"
serde_json = "1"
